theme: minimal-mistakes-jekyll
remote_theme: benbalter/retlab

title: Rachel's Blog
description: Rachel's Blog
show_downloads: false

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

minimal_mistakes_skin: "air"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true